# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - EvoMarket-Docker

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_6fbb128abd314a27b214963d2a19b8cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9826cdb7550a4509b260eec18f2ac7ea }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6fbb128abd314a27b214963d2a19b8cc }}/EvoMarket:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'EvoMarket-Docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b91411f6c7354c3dbfb4df47d56129e1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_6fbb128abd314a27b214963d2a19b8cc }}/EvoMarket:${{ github.sha }}'