name: dotnet package

on: 
  push:
    branches: develop

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Display dotnet version
        run: dotnet --version
