name: dotnet package

on: 
  push:
    branches: develop

jobs:
  deploy:
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      # - name: Display files
      #   run:  ls -la
      - name: Display dotnet version
        run: dotnet --version
      - name: Build
        working-directory: ./TCBApp
        run: docker-compose build
      - name: Deploy
        working-directory: ./TCBApp
        run: |
              docker-compose down
              docker-compose up -d
      
  
    
