name: dotnet package

on: 
  push:
    branches: develop

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Display files
        run:  ls -la
      - name: Display dotnet version
        run: dotnet --version
      - name: Shop Api
        run: dotnet publish EvoMarket/EvoMarket.Shop.Api/EvoMarket.Shop.Api.csproj -c release -o /home/abmu/apps/EvoMarketAPI/Shop
