name: dotnet package

on: 
  push:
    branches: develop

jobs:
  deploy:
    
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Build
        working-directory: ./EvoMarket
        run: docker-compose build
      - name: Deploy
        working-directory: ./EvoMarket
        run: |
              docker-compose down
              docker-compose up -d
      
  
    
