# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Checkout project
      run: cd EvoMarket/EvoMarket.Payment.Api/
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet public -c release -o /home/abmu/published/EvoMarket/payment-api/
